[module]
[module.hugoVersion]
min = "0.100.0"

baseURL = "/WhiteRabbitDandy/"
languageCode = "en-us"
title = "WhiteRabbitDandy"
theme = "WhiteRabbitDandy"

# Enable features
enableGitInfo = true
enableEmoji = true
enableRobotsTXT = true

# Default language
defaultContentLanguage = "en"

# Menu configuration
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4

# Site parameters
[params]
  # Site description
  description = "Your site description"
  
  # Author information
  author = "Your Name"
  
  # Social media links
  [params.social]
    github = "https://github.com/yourusername"
    twitter = "https://twitter.com/yourusername"
    
  # Search configuration
  [params.search]
    enable = true
    
  # Comments
  [params.comments]
    enable = true

  # Categories to ignore
  [params.ignore]
    categories = []

  # Banner showcase configuration
  [params.bannershowcase]
    categories = ["BookReview"]
    limit = 2

# Server configuration
[server]
  [[server.headers]]
    for = "/**"
    [server.headers.values]
      X-Frame-Options = "DENY"
      X-Content-Type-Options = "nosniff"
      X-XSS-Protection = "1; mode=block"
      Referrer-Policy = "strict-origin-when-cross-origin"

# Image processing
[imaging]
  resampleFilter = "lanczos"
  quality = 75
  anchor = "smart"
  [imaging.exif]
    disableDate = true
    disableLatLong = true
    includeFields = ""
    excludeFields = ""

# Static files
[static]
  # Ensure static files are copied to the output directory
  copy = true

# Media types
[mediaTypes]
  [mediaTypes."image/webp"]
    suffixes = ["webp"]
  [mediaTypes."image/jpeg"]
    suffixes = ["jpg", "jpeg"]
  [mediaTypes."image/png"]
    suffixes = ["png"]

# Output formats
[outputFormats]
  [outputFormats.WebP]
    mediaType = "image/webp"
    isImage = true
    isHTML = false
    isText = false
    notAlternative = true