[module]
[module.hugoVersion]
min = "0.100.0"

baseURL = "/Blog/"
languageCode = "en-us"
title = "Your Site Title"

[params]
  # Your site parameters here

[server]
  [[server.headers]]
    for = "/**"
    [server.headers.values]
      X-Frame-Options = "DENY"
      X-Content-Type-Options = "nosniff"
      X-XSS-Protection = "1; mode=block"
      Referrer-Policy = "strict-origin-when-cross-origin"

[imaging]
  resampleFilter = "lanczos"
  quality = 75
  anchor = "smart"

[static]
  # Ensure static files are copied to the output directory
  copy = true